[build]
  command = "echo done"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/callback"
  to = "/.netlify/functions/auth"
  status = 200
