functionsDirectory = "/Users/isfa/Sites/isfa-dev/oauth-proxy/netlify/functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/isfa/Sites/isfa-dev/oauth-proxy"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/isfa/Sites/isfa-dev/oauth-proxy"
command = "echo done"
functions = "/Users/isfa/Sites/isfa-dev/oauth-proxy/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[redirects]]
from = "/auth"
to = "/.netlify/functions/auth"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/callback"
to = "/.netlify/functions/auth"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]